# Generated by Django 5.1.2 on 2026-06-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='platforms.platform')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['platform', '-timestamp'], name='analytics_c_platfor_d52549_idx')],
            },
        ),
    ]
